### ISSUE TITLE
Implement shipping out functionality

### ISSUE THREAD

**Issue by SirGrordbort** [SirGrordbort/Alchemist#10]
Items need to be able to be shipped out to the towns

**Comment by SirGrordbort** [comment]
Items must be destroyed in the box and the towns must receive the items and process them.

**Comment by samonz** [comment]
I created a blueprint a while back that has this basic functionality - it's called package box in the static objects folder - if you call GetObjects on it it will return a list of ingredients that are inside it - then once you've finished with them call EmptyBox and it should destroy them all.

**Comment by SirGrordbort** [comment]
Need a way to convert shipped out ingredients to potions that can be applied to the town
