### ISSUE TITLE
Can pull out seeds but not replant them in the same pot

### ISSUE THREAD

**Issue by SirGrordbort** [SirGrordbort/Alchemist#40]

**Comment by samonz** [comment]
Fixed - used the same logic that the heating element and grow point uses - every frame it checks if the object that it thinks is planted there is still in a planted state, e.g. physics are not enabled - if not then the seed has been picked up so the state is reset to available. Not sure how performance heavy every interactable object doing that check is every frame but it should be fine unless we end up with 1000s of objects which we wont be.
